package com.pt.app.model;
// Generated Jun 4, 2017 1:26:36 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "mydb")
public class Address {

	private Integer idAddress;
	private Customer customer;
	private String primaryAddress;
	private String secondaryAddress;

	public Address() {
	}

	public Address(Customer customer, String primaryAddress) {
		this.customer = customer;
		this.primaryAddress = primaryAddress;
	}

	public Address(Customer customer, String primaryAddress, String secondaryAddress) {
		this.customer = customer;
		this.primaryAddress = primaryAddress;
		this.secondaryAddress = secondaryAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAddress", unique = true, nullable = false)
	public Integer getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(Integer idAddress) {
		this.idAddress = idAddress;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCustomer", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "PrimaryAddress", nullable = false, length = 50)
	public String getPrimaryAddress() {
		return this.primaryAddress;
	}

	public void setPrimaryAddress(String primaryAddress) {
		this.primaryAddress = primaryAddress;
	}

	@Column(name = "SecondaryAddress", length = 50)
	public String getSecondaryAddress() {
		return this.secondaryAddress;
	}

	public void setSecondaryAddress(String secondaryAddress) {
		this.secondaryAddress = secondaryAddress;
	}

}
