package com.pt.app.model;
// Generated Jun 4, 2017 1:26:36 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "mydb")
public class Customer {


	private Integer idCustomer;
	private String name;
	private String contactDetails;
	private String contact;
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Equipment> equipments = new HashSet<Equipment>(0);

	public Customer() {
	}

	public Customer(String name, String contactDetails) {
		this.name = name;
		this.contactDetails = contactDetails;
	}

	public Customer(String name, String contactDetails, String contact, Set<Address> addresses,
			Set<Equipment> equipments) {
		this.name = name;
		this.contactDetails = contactDetails;
		this.contact = contact;
		this.addresses = addresses;
		this.equipments = equipments;
	}

	public Customer(String name, String contactDetails, String contact, Set<Address> addresses) {
		super();
		this.name = name;
		this.contactDetails = contactDetails;
		this.contact = contact;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCustomer", unique = true, nullable = true)
	public Integer getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Integer idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "Name", nullable = true, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ContactDetails", nullable = true, length = 30)
	public String getContactDetails() {
		return this.contactDetails;
	}

	public void setContactDetails(String contactDetails) {
		this.contactDetails = contactDetails;
	}

	@Column(name = "Contact", length = 9)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public Set<Equipment> getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Set<Equipment> equipments) {
		this.equipments = equipments;
	}

}
