package com.pt.app.model;
// Generated Jun 4, 2017 1:26:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Sla generated by hbm2java
 */
@Entity
@Table(name = "sla", catalog = "mydb")
public class Sla  {


	private Integer idSla;
	private String sla;
	private Date contractStart;
	private Date contractEnd;
	private Date installationDate;
	private Set<Equipment> equipments = new HashSet<Equipment>(0);

	public Sla() {
	}

	public Sla(String sla, Date contractStart, Date contractEnd, Date installationDate) {
		this.sla = sla;
		this.contractStart = contractStart;
		this.contractEnd = contractEnd;
		this.installationDate = installationDate;
	}

	public Sla(String sla, Date contractStart, Date contractEnd, Date installationDate, Set<Equipment> equipments) {
		this.sla = sla;
		this.contractStart = contractStart;
		this.contractEnd = contractEnd;
		this.installationDate = installationDate;
		this.equipments = equipments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSLA", unique = true, nullable = true)
	public Integer getIdSla() {
		return this.idSla;
	}

	public void setIdSla(Integer idSla) {
		this.idSla = idSla;
	}

	@Column(name = "SLA", nullable = true, length = 15)
	public String getSla() {
		return this.sla;
	}

	public void setSla(String sla) {
		this.sla = sla;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ContractStart", nullable = true, length = 10)
	public Date getContractStart() {
		return this.contractStart;
	}

	public void setContractStart(Date contractStart) {
		this.contractStart = contractStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ContractEnd", nullable = true, length = 10)
	public Date getContractEnd() {
		return this.contractEnd;
	}

	public void setContractEnd(Date contractEnd) {
		this.contractEnd = contractEnd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "InstallationDate", nullable = true, length = 10)
	public Date getInstallationDate() {
		return this.installationDate;
	}

	public void setInstallationDate(Date installationDate) {
		this.installationDate = installationDate;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sla")
	public Set<Equipment> getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Set<Equipment> equipments) {
		this.equipments = equipments;
	}

}
